"""Add is_out_of_stock to Menu model

Revision ID: a4faf00d95a3
Revises: bcb03a49ffcf
Create Date: 2025-09-19 23:38:58.482214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4faf00d95a3'
down_revision: Union[str, Sequence[str], None] = 'bcb03a49ffcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('is_out_of_stock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'is_out_of_stock')
    # ### end Alembic commands ###
